package CalcApp;


/**
* CalcApp/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calc.idl
* Wednesday, 13 May, 2026 1:11:01 PM IST
*/

public interface CalcOperations 
{
  float add (float a, float b);
} // interface CalcOperations
